<?php
// $Id$

//   grinlegumes.module

// Sudhansu Dash
// 2015 Nov 30


/**
 * Implements hook_menu().
 */

function grinlegumes_menu() {
  $items = array();
  $items['germplasm/grin/grinlegumes'] = array( //this creates a URL
    'title' => 'GRIN Germplasm Data at LIS', //page title
    'description' => 'A form to acces USDA GRIN germplasm accession data for legumes stored at LIS.',
    'page callback' => grinlegumes_page_callback, //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    //'page arguments' => array('grin_acc_query_form'), //form name here // may be not reqd if page callback fn() doesn't need it.
    'access callback' => TRUE,
  );
  return $items;
}


/**
 * Implements hook_theme().
 */

function grinlegumes_theme() {
  return array(
    'grinlegumes_page_template' => array(  // this array name to be used in theme()
      'template' => 'grinlegumes_page', // template file grinlegumes_page.tpl.php
      'variables' => array('examples' => NULL, 'grin_taxon' => NULL, 'acc_no' => NULL, 'html_content' => NULL),
        ),
    );
}


/**
 * Implements page callback.
 */

function grinlegumes_page_callback() {
  
  //Get the grin_acc_no from URL
  $acc_no = $_GET['grin_acc_no'];
  
  //Process accn number: separate prefix and no.
  preg_match('/(?<prefix>[aA-zZ]*)\s*(?<number>\d+)/',$acc_no,$matches);
  $acc_no_prefix = $matches[prefix];  
  $acc_no_num = $matches[number]; 
  $acc_no_full = $acc_no_prefix." ".$acc_no_num;

  //If prefixed use full acc no. else use just the no.
  if ($acc_no_prefix) {
    $acc_no = $acc_no_full;
  } else {
  $acc_no = $acc_no_num;
  }
  
  //Genus
  $genus = $_GET['grin_taxon'];
  
  //Example acc nos.
  $examples = <<<EXAMPLES
    <div id="examples"  style="font-size:80%;">
    <b>Examples. </b>
    Chickpea:
    <a href="#" onclick='document.getElementById("grin_acc_no").value=this.innerHTML;'>PI 374113</a>,&nbsp
    <a href="#" onclick='document.getElementById("grin_acc_no").value=this.innerHTML;'>PI 489777</a>;&nbsp 
    Peanut:&nbsp;  
    <a href="#" onclick='document.getElementById("grin_acc_no").value=this.innerHTML;'>Grif 236</a>,&nbsp 
    <a href="#" onclick='document.getElementById("grin_acc_no").value=this.innerHTML;'>PI 289619</a>,&nbsp 
    <a href="#" onclick='document.getElementById("grin_acc_no").value=this.innerHTML;'>PI 565448</a> 
    .
    </div>
EXAMPLES;
 
  //Query database:
  //Using Drupal database API db_select
  $query = db_select('lis_germplasm.legumes_grin_evaluation_data', 'lged');
  $query->innerjoin('lis_germplasm.grin_accession','ga','lged.accession_prefix||\' \'||lged.accession_number = ga.accenumb');
  $query->fields('lged',array('accession_prefix','accession_number','descriptor_name','observation_value','method_name','taxon','accession_comment'));//SELECT the fields from table
  $query->fields('ga',array('accenumb','origcty','latitude','longitude','latdec','longdec','elevation','cropname','acqdate','colldate','collsite','spauthor','avail','instcode','duplsite','donornumb','storage','accename','history'));//SELECT the fields from table
  $query->orderBy('lged.method_name');//first by the evaluation study
  $query->orderBy('lged.descriptor_name','ASC');//next by descriptor name
  //If prefixed, query ga-field with full acc else query jus no in lged-field 
  if ($acc_no_prefix){
    $query->condition('ga.accenumb',$acc_no,'=');
  } else {
    $query->condition('lged.accession_number',$acc_no,'=');
  }
  $query->condition('lged.taxon',$genus.'%','LIKE'); //now, searching by genus is not useful

  //Result
  $result = $query->execute();
  $row_count_result = $result->rowCount();
  
  //Result to a php array
  $result_array = array();
  if ($row_count_result) {
    foreach($result as $row) {
      $result_array[] = $row;
    }
  } 

    //database query into html and in a variable
    if (!$row_count_result) { 
      $html_content = "This acc no has no data, please check for correctness!";
    } else {
      //Passport data:   (Link to grinconnect/query?grin_acc_no=PI+489777#)
      $html_content_passport = 
	 "<div>"
	 ."<fieldset>"
	 ."<legend>Available passport data for <b>".$result_array[0]->accession_prefix.' '.$result_array[0]->accession_number."</b></legend>"
	 ."<br/>"
	 ."<b>Accession number:</b>&nbsp;".$result_array[0]->accession_prefix.' '.$result_array[0]->accession_number."&nbsp;"
	 ."(<a href=\"/grinconnect/query?grin_acc_no=".$result_array[0]->accession_prefix."+".$result_array[0]->accession_number."\">link to GRIN</a>)"."&nbsp;&nbsp;&nbsp;&nbsp;"
	 ."<b>Taxon:</b>&nbsp;".unknown_if_empty($result_array[0]->taxon)."&nbsp;(<b>Author:</b>&nbsp".unknown_if_empty($result_array[0]->spauthor).")"."&nbsp;&nbsp;&nbsp;&nbsp;"
	 ."<b>Crop:</b>&nbsp;".unknown_if_empty($result_array[0]->cropname)."&nbsp;&nbsp;&nbsp;&nbsp;"
	 ."<b>Accession name:</b>&nbsp;".unknown_if_empty($result_array[0]->accename)."&nbsp;&nbsp;&nbsp;&nbsp;"
	 ."<br/>"
	 ."<b>Country of origin:</b>&nbsp;".unknown_if_empty($result_array[0]->origcty)."&nbsp;&nbsp;&nbsp;&nbsp;"
	 ."<b>Site of collection:</b>&nbsp;".unknown_if_empty($result_array[0]->collsite)."&nbsp;&nbsp;&nbsp;&nbsp;"
	 ."<b>Latitude:</b>&nbsp;".unknown_if_empty($result_array[0]->latdec)."&nbsp;&nbsp;&nbsp;&nbsp;"
	 ."<b>Longitude:</b>&nbsp;".unknown_if_empty($result_array[0]->longdec)."&nbsp;&nbsp;&nbsp;&nbsp;"
	 ."<b>Elevation:</b>&nbsp;".unknown_if_empty($result_array[0]->elevation)."&nbsp;&nbsp;&nbsp;&nbsp;"
	 ."<br/>"
	 ."<b>History:</b>&nbsp;".unknown_if_empty($result_array[0]->history)."&nbsp;&nbsp;&nbsp;&nbsp;"
	 ."<br/>"
	 .blank_if_empty($result_array[0]->accession_comment,"<b>Comments:</b>&nbsp;")
	 ."<br/>"
	 ."<b>Date of acquisition:</b>&nbsp;".unknown_if_empty($result_array[0]->acqdate)."&nbsp;&nbsp;&nbsp;&nbsp;"
	 ."<b>Date of collection:</b>&nbsp;".unknown_if_empty($result_array[0]->colldate)."&nbsp;&nbsp;&nbsp;&nbsp;"
	 ."<br/>"
	 ."<b>Institution code/Available at:</b>&nbsp;".unknown_if_empty($result_array[0]->instcode)."&nbsp;&nbsp;&nbsp;&nbsp;"
	 ."<b>Duplication/Backup site:</b>&nbsp;".unknown_if_empty($result_array[0]->duplsite)."&nbsp;&nbsp;&nbsp;&nbsp;"
	 ."<b>Availability:</b>&nbsp;".unknown_if_empty($result_array[0]->avail)."&nbsp;&nbsp;&nbsp;&nbsp;"
	 ."<br/>";

         //if lat-long available provide link to map
         if ($result_array[0]->latdec != 0 OR $result_array[0]->longdec != 0) {
	 $html_content_passport .="<a href=\"/germplasm/map/#?accessionIds=".$result_array[0]->accession_prefix.' '.$result_array[0]->accession_number."\" "." target='_blank'>"."<b>See it in a map</b></a>";
	 } else { 
	 $html_content_passport .="(No map data is available for this accession.)";
	 }

	 $html_content_passport .="</fieldset>"  // close fieldset and div
	 ."</div>";

      //Evaluation data:
      $html_content_eval = 
	 "<fieldset>"
	 ."<legend>Available trait evaluation data for <b>".$result_array[0]->accession_prefix.' '.$result_array[0]->accession_number."</b></legend>"
	 ."<br/>"
	 ."<table>"
	 ."<tr>"
	 ."<td>"."<b>TRAIT</b><br/>(descriptor_name)"."</td>"."<td>"."<b>VALUE</b><br/>(observation_value)"."</td>"."<td>"."<b>EVALUATION STUDY</b><br/>(method_name)"."</td>"
	 //."<td>"."ACCESSION NO.<br/>(GRIN)"."</td>"."<td>"."TRAIT<br/>(descriptor_name)"."</td>"."<td>"."observation_value"."</td>"."<td>"."EVALUATION STUDY<br/>(method_name)"."</td>"."<td>"."Taxon"."</td>"
	 ."</tr>";
      
      foreach($result_array as $row) {
	$html_content_eval = $html_content_eval .= 
	  "<tr>"
	  //."<td>".$row->accession_prefix.' '.$row->accession_number."</td>"
	  //."<td>".$row['accession_number']."</td>"
	  ."<td>".$row->descriptor_name."</td>"
	  //."<td>".$row['descriptor_name']."</td>"
	  ."<td>".$row->observation_value."</td>"
	    //."<td>".$row->['observation_value']."</td>"
	  ."<td>".$row->method_name."</td>"
	  //."<td>".$row['method_name']."</td>"
	  //."<td>".$row->taxon."</td>"
	  ."</tr>";
	
      } //foreach
      
      $html_content_eval .= "</table>";
      $html_content_eval .= "</fieldset>";

      $html_content = $html_content_passport.$html_content_eval;

    }  //if-else

  
  // array name in hook_theme() that specifies page template file.
  return theme ('grinlegumes_page_template', array('examples' => $examples, 'grin_taxon' => $genus, 'acc_no' => $acc_no, 'html_content' => $html_content, 'acc_no_prefix' => $acc_no_prefix, 'acc_no_num' => $acc_no_num)); 

}

/**
* Print Unknown if empty
*/

  //If $xyz has no values, print unknown
function unknown_if_empty ($xyz) {
  if ($xyz) {
    return $xyz;
  } else {
    return "Not known";
  }//if
} //fn

/**
* Blank if empty (print nothing at all
*/

  //if $xyz has a value, print the $specific_label then $xyz, else return null
function blank_if_empty ($xyz,$specific_label) {
  if ($xyz) {
    return $specific_label."&nbsp;".$xyz;
  } else {
    return "";
  }//if
} //fn





//  SCRATCH PAD
//=============


