<?php
// $Id$

//   grinlegumes.module

// Sudhansu Dash
// 2015 Nov 30


/**
 * Implements hook_menu().
 */

function grinlegumes_menu() {
  $items = array();
  $items['germplasm/grin/grinlegumes'] = array( //this creates a URL
    'title' => 'GRIN Germplasm Data at LIS', //page title
    'description' => 'A form to acces USDA GRIN germplasm accession data for legumes stored at LIS.',
    'page callback' => grinlegumes_page_callback, //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    //'page arguments' => array('grin_acc_query_form'), //form name here // may be not reqd if page callback fn() doesn't need it.
    'access callback' => TRUE,
    
  );

  return $items;
}


/**
 * Implements hook_theme().
 */

function grinlegumes_theme() {
  return array(
    'grinlegumes_page_template' => array(  // this array name to be used in theme()
      'template' => 'grinlegumes_page', // template file grinlegumes_page.tpl.php
      'variables' => array('examples' => NULL, 'grin_url' => NULL, 'grin_taxon' => NULL, 'acc_no' => NULL, 'html_content' => NULL),
        ),
    );
}

/**
 * Implements page callback.
 */

function grinlegumes_page_callback() {
  
  //Get the grin_acc_no from URL
  $acc_no = $_GET['grin_acc_no'];
  
  //Process accn number: separate prefix and no.
  preg_match('/(?<prefix>[aA-zZ]*)\s*(?<number>\d+)/',$acc_no,$matches);
  $acc_no_prefix = $matches[prefix];  
  $acc_no_num = $matches[number]; 
  $acc_no_full = $acc_no_prefix." ".$acc_no_num;

  //If prefixed use full acc no. else use just the no.
  if ($acc_no_prefix) {
    $acc_no = $acc_no_full;
  } else {
  $acc_no = $acc_no_num;
  }
  
  //Genus
  $genus = $_GET['grin_taxon'];
  
  //Example acc nos.
  $examples = select_grinlegumes_examples();
  
  //Query database:
  //Using Drupal database API db_select
  $query2 = db_select('lis_germplasm.legumes_grin_evaluation_data', 'lged');
  $query2->innerjoin('lis_germplasm.grin_accession','ga','lged.accession_prefix||\' \'||lged.accession_number = ga.accenumb');
  $query2->fields('lged',array('accession_prefix','accession_number','descriptor_name','observation_value','method_name','taxon'));//SELECT the fields from table
  $query2->fields('ga',array('accenumb','origcty','latitude','longitude','elevation'));//SELECT the fields from table
  $query2->orderBy('lged.method_name');//first by the evaluation study
  $query2->orderBy('lged.descriptor_name','ASC');//next by descriptor name
  //If prefixed, query ga-field with full acc else query jus no in lged-field 
  if ($acc_no_prefix){
    $query2->condition('ga.accenumb',$acc_no,'=');
  } else {
    $query2->condition('lged.accession_number',$acc_no,'=');
  }
  $query2->condition('lged.taxon',$genus.'%','LIKE'); //now, searching by genus is not useful

  //Result
  $result_psql2 = $query2->execute();
  $row_count_result_psql2 = $result_psql2->rowCount();
  
  //Result to a php array
  $result2_array = array();
  if ($row_count_result_psql2) {
    foreach($result_psql2 as $row) {
      $result2_array[] = $row;
    }
  } 

    //database query into html table and in a variable
    if (!$row_count_result_psql2) { 
      $html_content = "This acc no for genus, <i>".$genus."</i> has no data, please check for correctness!";
    } else {
        $html_content = 
	   "<div>"
	   ."Your Query: ".$result2_array[0]->accession_prefix.' '.$result2_array[0]->accession_number."<br/>"
	   ."Country of Origin: ".$result2_array[0]->origcty."<br/>"
	   ."</div>"
	   ."<table>"
           ."<tr>"
           ."<td>"."ACCESSION NO.<br/>(GRIN)"."</td>"."<td>"."TRAIT<br/>(descriptor_name)"."</td>"."<td>"."observation_value"."</td>"."<td>"."EVALUATION STUDY<br/>(method_name)"."</td>"."<td>"."Taxon"."</td>"
           ."</tr>";
        
       foreach($result2_array as $row) {
          $html_content = $html_content .= 
            "<tr>"
            ."<td>".$row->accession_prefix.' '.$row->accession_number."</td>"
            //."<td>".$row['accession_number']."</td>"
            ."<td>".$row->descriptor_name."</td>"
            //."<td>".$row['descriptor_name']."</td>"
            ."<td>".$row->observation_value."</td>"
	      //."<td>".$row->['observation_value']."</td>"
            ."<td>".$row->method_name."</td>"
            //."<td>".$row['method_name']."</td>"
            ."<td>".$row->taxon."</td>"
            ."</tr>";
          
        } //foreach
        
        $html_content .= "</table>";
     
      }  //if-else

  
  // array name in hook_theme() that specifies page template file.
  return theme ('grinlegumes_page_template', array('examples' => $examples, 'grin_url' => $grin_url, 'grin_taxon' => $genus, 'acc_no' => $acc_no, 'html_content' => $html_content, 'acc_no2' => $acc_no2, 'acc_no_prefix' => $acc_no_prefix, 'acc_no_num' => $acc_no_num)); 

}




/*                 PI 374113, PI 489777      */




/**
 * Select example based on http_host (peanutbase or LIS).
 */

function select_grinlegumes_examples() {
	##function select_chickpeagrindata_examples() {
  
  //Find corresponding example html for peanutbase or LIS
  //Passed on using $examples via hook_theme() and theme()
  
    $examples = <<<EXAMPLES
        <div id="examples"  style="font-size:80%;">
        <b>Examples. </b>
	Chickpea:
        <a href="#" onclick='document.getElementById("grin_acc_no").value=this.innerHTML;'>PI 374113</a>,&nbsp
        <a href="#" onclick='document.getElementById("grin_acc_no").value=this.innerHTML;'>PI 489777</a>;&nbsp 
        Peanut:&nbsp;  
	<a href="#" onclick='document.getElementById("grin_acc_no").value=this.innerHTML;'>Grif 236</a>,&nbsp 
	<a href="#" onclick='document.getElementById("grin_acc_no").value=this.innerHTML;'>PI 289619</a>,&nbsp 
	<a href="#" onclick='document.getElementById("grin_acc_no").value=this.innerHTML;'>PI 565448</a> 
	.
        </div>
EXAMPLES;

  return $examples;
}

//  SCRATCH PAD
//=============


